let analysis=null,activeFrame="1D",loading=false,drag=null,chartView=null;
const layers={zones:true,trend:true,levels:true,averages:true,indicators:true};
const viewState={};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const num=(v,d=2)=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v))?Number(v).toFixed(d):"—";
const money=v=>Number.isFinite(Number(v))?`$${Number(v).toFixed(2)}`:"—";
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2400)}
function polyline(points,key,x,y){return points.map((p,i)=>p[key]==null?null:`${x(i).toFixed(1)},${y(Number(p[key])).toFixed(1)}`).filter(Boolean).join(" ")}
function levelLine(value,text,tone,width,y){if(!Number.isFinite(Number(value)))return"";const yy=y(Number(value)),color=tone==="stop"?"#ef6a67":tone==="target"?"#27c499":"#68788a";return `<line x1="66" y1="${yy}" x2="${width-76}" y2="${yy}" class="level-${tone}"/><rect x="${width-74}" y="${yy-10}" width="70" height="20" rx="4" fill="${color}"/><text x="${width-39}" y="${yy+4}" text-anchor="middle" fill="#fff" class="level-label">${esc(text)}</text>`}
function fullPoints(){return analysis?.timeframes?.[activeFrame]?.chart||[]}
function defaultCount(total){const compact=matchMedia("(max-width:560px)").matches;return Math.min(total,compact?(activeFrame==="1W"?36:activeFrame==="1D"?42:48):(activeFrame==="1W"?72:activeFrame==="1D"?110:96))}
function currentWindow(){const all=fullPoints(),total=all.length;let state=viewState[activeFrame];if(!state){state=viewState[activeFrame]={count:defaultCount(total),end:total}}state.count=Math.max(Math.min(24,total),Math.min(state.count,total));state.end=Math.max(state.count,Math.min(state.end,total));return{all,total,state,start:state.end-state.count,points:all.slice(state.end-state.count,state.end)}}
function setWindow(count,end){const total=fullPoints().length;if(!total)return;const min=Math.min(24,total),state=viewState[activeFrame]||(viewState[activeFrame]={});state.count=Math.max(min,Math.min(total,Math.round(count)));state.end=Math.max(state.count,Math.min(total,Math.round(end)));renderChart()}
function resetWindow(){const total=fullPoints().length;viewState[activeFrame]={count:defaultCount(total),end:total};renderChart()}
function timeLabel(t){const s=String(t||"").replace("T"," ");return ["15m","1h","4h"].includes(activeFrame)?s.slice(5,16):s.slice(0,10)}

function renderChart(){
  if(!analysis)return;const frame=analysis.timeframes?.[activeFrame];if(!frame?.sufficient){$("chart").innerHTML='<p class="loading">该周期数据不足。</p>';return}
  const windowData=currentWindow(),points=windowData.points;if(points.length<10){$("chart").innerHTML='<p class="loading">K线数量不足。</p>';return}
  const chartBox=$("chart"),height=760,compact=matchMedia("(max-width:560px)").matches;
  const width=compact?Math.max(360,Math.round((chartBox.clientWidth||360)*height/Math.max(chartBox.clientHeight||600,1))):1440;
  const rec=analysis.recommendation||{},left=66,right=76,plotWidth=width-left-right;
  const priceTop=18,priceBottom=388,volumeTop=402,volumeBottom=468,macdTop=500,macdBottom=592,rsiTop=626,rsiBottom=716;
  const prices=points.flatMap(p=>[p.h,p.l,layers.averages?p.ma20:null,layers.averages?p.ma50:null]).map(Number).filter(Number.isFinite);
  if(layers.levels)[rec.entry,rec.stop,rec.target].map(Number).filter(Number.isFinite).forEach(v=>prices.push(v));
  let low=Math.min(...prices),high=Math.max(...prices),padding=Math.max((high-low)*.07,high*.0025);low-=padding;high+=padding;
  const py=v=>priceTop+(high-v)/(high-low||1)*(priceBottom-priceTop),step=plotWidth/points.length,x=i=>left+step*i+step/2,cw=Math.max(1.6,Math.min(9,step*.62));let svg="";
  for(let i=0;i<6;i++){const ratio=i/5,y=priceTop+ratio*(priceBottom-priceTop),label=high-ratio*(high-low);svg+=`<line x1="${left}" y1="${y}" x2="${width-right}" y2="${y}" class="grid-line"/><text x="5" y="${y+4}" class="axis-text">$${label.toFixed(2)}</text>`}
  if(layers.zones){const planYs=[rec.entry,rec.stop,rec.target].map(Number).filter(Number.isFinite).map(py),used=[];svg+=(frame.zones||[]).slice(0,5).map(z=>{const labelY=py(Number(z.high))+12,show=planYs.every(y=>Math.abs(y-labelY)>17)&&used.every(y=>Math.abs(y-labelY)>17);if(show)used.push(labelY);return `<rect x="${left}" y="${py(Number(z.high))}" width="${plotWidth}" height="${Math.max(2,py(Number(z.low))-py(Number(z.high)))}" class="${z.role==='支撑'?'zone-support':'zone-resistance'}"/>${show?`<text x="${width-right-5}" y="${labelY}" text-anchor="end" class="axis-text">${esc(z.role)} ${money(z.level)} · ${z.touches}次</text>`:''}`}).join("")}
  const maxVolume=Math.max(...points.map(p=>Number(p.v)||0),1);
  svg+=points.map((p,i)=>{const o=Number(p.o),c=Number(p.c),up=c>=o,cls=up?'candle-up':'candle-down',bodyY=Math.min(py(o),py(c)),bodyH=Math.max(1.5,Math.abs(py(o)-py(c))),vh=(Number(p.v)||0)/maxVolume*(volumeBottom-volumeTop);return `<line x1="${x(i)}" y1="${py(Number(p.h))}" x2="${x(i)}" y2="${py(Number(p.l))}" class="${cls}"/><rect x="${x(i)-cw/2}" y="${bodyY}" width="${cw}" height="${bodyH}" class="${cls}"/><rect x="${x(i)-cw/2}" y="${volumeBottom-vh}" width="${cw}" height="${vh}" class="${up?'volume-up':'volume-down'}"/>`}).join("");
  if(layers.averages){svg+=`<polyline points="${polyline(points,'ma20',x,py)}" class="ma20-line"/><polyline points="${polyline(points,'ma50',x,py)}" class="ma50-line"/>`}
  if(layers.trend&&frame.trendlines){const localStart=Math.max(0,points.length-30);for(const key of ["upper","lower"]){const line=frame.trendlines[key];if(line)svg+=`<line x1="${x(localStart)}" y1="${py(Number(line.start))}" x2="${x(points.length-1)}" y2="${py(Number(line.end))}" class="trend-line"/>`}}
  if(layers.levels){svg+=levelLine(rec.entry,`入 ${num(rec.entry)}`,"entry",width,py)+levelLine(rec.stop,`损 ${num(rec.stop)}`,"stop",width,py)+levelLine(rec.target,`目 ${num(rec.target)}`,"target",width,py)}
  const topPattern=(analysis.patterns||[]).find(p=>p.timeframe===activeFrame);if(topPattern){const px=Math.max(left+120,x(points.length-12)),yy=priceTop+30;svg+=`<text x="${px}" y="${yy}" text-anchor="middle" class="pattern-callout">${esc(topPattern.name)} · ${esc(topPattern.status)}</text><line x1="${px}" y1="${yy+7}" x2="${x(points.length-5)}" y2="${py(Number(points[points.length-5].h))-7}" class="pattern-arrow"/>`}
  svg+=`<line x1="${left}" y1="${volumeTop-7}" x2="${width-right}" y2="${volumeTop-7}" class="grid-line"/><text x="6" y="${volumeTop+12}" class="chart-label">VOL</text>`;
  if(layers.indicators){const values=points.flatMap(p=>[p.macd,p.macd_signal,p.macd_hist]).map(Number).filter(Number.isFinite),maxAbs=Math.max(...values.map(Math.abs),.0001),my=v=>(macdTop+macdBottom)/2-v/maxAbs*(macdBottom-macdTop)*.42,zero=my(0);svg+=`<line x1="${left}" y1="${zero}" x2="${width-right}" y2="${zero}" class="grid-line"/><text x="6" y="${macdTop+14}" class="chart-label">MACD 12·26·9</text>`;svg+=points.map((p,i)=>{const v=Number(p.macd_hist);if(!Number.isFinite(v))return"";const yy=my(v);return `<rect x="${x(i)-cw/2}" y="${Math.min(yy,zero)}" width="${cw}" height="${Math.max(1,Math.abs(yy-zero))}" class="${v>=0?'hist-positive':'hist-negative'}"/>`}).join("");svg+=`<polyline points="${polyline(points,'macd',x,my)}" class="macd-line"/><polyline points="${polyline(points,'macd_signal',x,my)}" class="signal-line"/>`;const ry=v=>rsiTop+(100-v)/100*(rsiBottom-rsiTop);svg+=`<text x="6" y="${rsiTop+14}" class="chart-label">RSI 14</text><line x1="${left}" y1="${ry(70)}" x2="${width-right}" y2="${ry(70)}" class="threshold"/><line x1="${left}" y1="${ry(30)}" x2="${width-right}" y2="${ry(30)}" class="threshold"/><text x="${width-right+8}" y="${ry(70)+4}" class="axis-text">70</text><text x="${width-right+8}" y="${ry(30)+4}" class="axis-text">30</text><polyline points="${polyline(points,'rsi14',x,ry)}" class="rsi-line"/>`}
  const tickSet=[0,.25,.5,.75,1].map(v=>Math.min(points.length-1,Math.round((points.length-1)*v)));svg+=tickSet.map(i=>`<text x="${x(i)}" y="${height-10}" text-anchor="middle" class="axis-text">${esc(timeLabel(points[i].t))}</text>`).join("");
  $("chart").innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="QQQ ${esc(activeFrame)} 交互式K线、成交量、MACD、RSI和计划价位">${svg}</svg>`;
  chartView={points,start:windowData.start,total:windowData.total,left,right,width,priceY:py,x};const slider=$("rangeSlider");slider.min=String(windowData.state.count);slider.max=String(windowData.total);slider.value=String(windowData.state.end);slider.disabled=windowData.total<=windowData.state.count;$("rangeLabel").textContent=`显示 ${windowData.state.count} / ${windowData.total} 根`;
  $("chartMeta").textContent=`${activeFrame} · 常规交易时段 · 当前 ${timeLabel(points[0].t)} 至 ${timeLabel(points.at(-1).t)} · 完整度 ${num(frame.quality?.ohlcv_complete_pct,1)}%`;
}

function renderTimeframes(){const order=["15m","1h","4h","1D","1W"];$("timeframes").innerHTML=order.map(label=>{const f=analysis.timeframes?.[label];return `<button data-frame="${label}" class="${label===activeFrame?'active':''} ${!f?.sufficient?'unavailable':''}">${label}</button>`}).join("");document.querySelectorAll("[data-frame]").forEach(b=>b.onclick=()=>{if(!analysis.timeframes?.[b.dataset.frame]?.sufficient)return;activeFrame=b.dataset.frame;renderTimeframes();renderChart()})}
function updateTarget(){if(!analysis)return;const rr=Number($("rrSlider").value),r=analysis.recommendation||{},entry=Number(r.entry),stop=Number(r.stop),risk=Math.abs(entry-stop),target=r.side==="SHORT"?entry-risk*rr:entry+risk*rr;$("rrValue").textContent=`${rr.toFixed(1)}:1`;$("target").textContent=money(target);r.target=Number(target.toFixed(2));renderChart()}
function render(){
  const r=analysis.recommendation||{},m=analysis.market_context||{},q=m.qqq||{},d=analysis.data||{},change=Number(q.day_change_pct);$("price").textContent=money(analysis.price);$("change").textContent=Number.isFinite(change)?`${change>=0?'▲':'▼'} ${Math.abs(change).toFixed(2)}%`:"涨跌幅 —";$("change").style.color=change>=0?'var(--green)':'var(--red)';$("grade").textContent=r.grade||"—";$("gradeScore").textContent=`${num(r.score,0)} / 100`;$("freshness").textContent=`${d.provider||'数据源未知'} · ${String(d.quote_time||'').replace('T',' ').slice(0,16)}`;
  const gate=d.execution_ready?{cls:"ready",text:"行情时效闸门已通过；仍需人工确认价格与仓位。"}:{cls:"blocked",text:"当前为公开近实时或非盘中数据；可用于制定计划，实际执行前请用券商实时价格复核。"};$("dataGate").className=`notice ${gate.cls}`;$("dataGate").textContent=gate.text;$("signalHeadline").textContent=r.headline||"—";$("stance").textContent=r.stance||"—";$("signalBanner").className=`signal-banner panel ${r.side==='SHORT'?'short':'long'}`;$("nextCondition").textContent=r.next_condition||"—";
  $("riskPct").textContent=`${num(r.risk_pct)}%`;$("entry").textContent=money(r.entry);$("stop").textContent=money(r.stop);$("target").textContent=money(r.target);$("execution").textContent=r.execution_ready?"进入人工执行核对":r.technical_setup_ready?"技术条件完成，等待实时数据":"尚未触发";$("rrSlider").value=String(r.risk_reward||2);$("rrValue").textContent=`${num(r.risk_reward,1)}:1`;
  const direction={BULLISH:"看多",BEARISH:"看空",NEUTRAL:"中性"},patterns=(analysis.patterns||[]).slice(0,5);$("patternCount").textContent=`${analysis.patterns?.length||0} 个结构`;$("patternSummary").innerHTML=patterns.length?patterns.map(p=>`<div class="pattern-row"><b>${esc(p.name)}</b><span>${esc(p.timeframe)} · ${direction[p.direction]||esc(p.direction)} · ${esc(p.status)}</span><em>规则强度 ${num(p.confidence,0)}</em></div>`).join(""):'<p class="loading">当前没有达到规则阈值的结构形态。</p>';
  const breadth=m.breadth||{},vix=m.vix||{};$("marketScore").textContent=`${m.regime_label||'—'} · ${m.score??'—'}/100`;$("marketSummary").innerHTML=`<article class="market-stat"><span>QQQ位置</span><b>${esc(m.position_label||'—')}</b><small>${esc(m.action||'')}</small></article><article class="market-stat"><span>观察池宽度</span><b>${num(breadth.above_ma50_pct,1)}%</b><small>站上50日线 · 样本${breadth.sample_size||0}</small></article><article class="market-stat"><span>VIX</span><b>${num(vix.price,2)}</b><small>日变动 ${num(vix.day_change_pct,2)}%</small></article><article class="market-stat"><span>QQQ 20日回报</span><b>${num(q.return20_pct,2)}%</b><small>距52周高点 ${num(q.distance_high_52w_pct,2)}%</small></article>`;
  $("logic").innerHTML=(r.logic||[]).map(x=>`<li>${esc(x)}</li>`).join("");$("vetoes").innerHTML=(r.vetoes||[]).map(x=>`<span class="veto">${esc(x)}</span>`).join("");$("method").textContent=r.method||"—";const methodLabels={rsi:"RSI",atr:"ATR",macd:"MACD",session:"K线时段",zones:"支撑阻力",honesty:"评分含义"};$("methodology").innerHTML=Object.entries(r.methodology||{}).map(([k,v])=>`<div class="method-row"><span>${methodLabels[k]||esc(k)}</span><b>${esc(v)}</b></div>`).join("");
  const frames=["15m","1h","4h","1D","1W"];$("detailContent").innerHTML=`<div class="detail-grid">${frames.map(label=>{const f=analysis.timeframes?.[label],i=f?.indicators||{};return `<article><span>${label}</span><b>${f?.sufficient?`${f.trend} · ${f.trend_score>0?'+':''}${f.trend_score}`:'数据不足'}</b><small>RSI ${num(i.rsi14,1)} · MACD ${num(i.macd,3)} · ATR ${num(i.atr_pct,2)}%</small></article>`}).join("")}</div><div class="detail-grid"><article><span>同向趋势历史样本</span><b>${analysis.backtest?.sample_count||0}</b><small>不是相同形态胜率</small></article>${[5,10,20].map(day=>{const row=analysis.backtest?.[`day_${day}`]||{};return `<article><span>${day}根K线后</span><b>${row.win_rate==null?'样本不足':num(row.win_rate,1)+'%'}</b><small>同向中位回报 ${row.median_return_pct==null?'—':num(row.median_return_pct,2)+'%'}</small></article>`}).join("")}</div>`;
  $("copilotState").textContent=`${r.stance||'观望'} · QQQ @ ${num(analysis.price)} · 完成度 ${num(r.score,0)}`;$("copilotAnswer").textContent=r.next_condition||"等待下一条件。";activeFrame=analysis.timeframes?.[activeFrame]?.sufficient?activeFrame:(analysis.timeframes?.["1D"]?.sufficient?"1D":analysis.available_timeframes?.[0]);renderTimeframes();renderChart();maybeNotify(r)
}
function copilotAnswer(q){const r=analysis?.recommendation||{},answers={why:(r.logic||[]).join(" "),buy:r.execution_ready?"规则和数据闸门均通过，但仍需人工核对价格、仓位和止损。":r.technical_setup_ready?"技术条件已完成，但实时数据闸门未通过，不能把它当作即时下单指令。":`当前不满足完整条件。${r.next_condition||''}`,next:r.next_condition||"等待多周期确认。",risk:(r.vetoes||[]).join("；")||`失效价 ${money(r.stop)}，单价风险约 ${num(r.risk_pct)}%。`};$("copilotAnswer").textContent=answers[q]||r.next_condition}
function maybeNotify(r){const key="qqq-rule-state",old=localStorage.getItem(key);if(old&&old!==r.state&&r.technical_setup_ready&&Notification.permission==="granted")new Notification(`QQQ ${r.stance}提醒`,{body:`${r.headline}；计划入场 ${money(r.entry)}，失效 ${money(r.stop)}`});localStorage.setItem(key,r.state||"UNKNOWN")}
async function load(){if(loading)return;loading=true;$("refreshBtn").disabled=true;try{const res=await fetch("/api/qqq-analysis",{cache:"no-store"}),data=await res.json();if(!res.ok)throw new Error(data.error||"读取失败");analysis=data;render()}catch(e){$("dataGate").className="notice blocked";$("dataGate").textContent=`分析暂不可用：${e.message}`;toast(e.message)}finally{loading=false;$("refreshBtn").disabled=false}}
function zoom(factor,anchor=.5){if(!analysis)return;const {state,start,total}=currentWindow(),newCount=Math.round(state.count*factor),anchorIndex=start+state.count*anchor,newStart=anchorIndex-newCount*anchor;setWindow(newCount,newStart+newCount)}
const chart=$("chart");chart.addEventListener("wheel",e=>{if(!analysis)return;e.preventDefault();const rect=chart.getBoundingClientRect(),anchor=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width));zoom(e.deltaY<0?.82:1.22,anchor)},{passive:false});chart.addEventListener("pointerdown",e=>{if(!analysis||e.button!==0)return;const state=currentWindow().state;drag={x:e.clientX,end:state.end,count:state.count,moved:false};chart.setPointerCapture(e.pointerId);chart.classList.add("dragging")});chart.addEventListener("pointermove",e=>{if(drag){const dx=e.clientX-drag.x;if(Math.abs(dx)>3)drag.moved=true;const shift=Math.round(dx/chart.getBoundingClientRect().width*drag.count);setWindow(drag.count,drag.end-shift);return}if(!chartView)return;const rect=chart.getBoundingClientRect(),ratio=(e.clientX-rect.left)/rect.width,plotRatio=(ratio-chartView.left/chartView.width)/(1-(chartView.left+chartView.right)/chartView.width);if(plotRatio<0||plotRatio>1){$("chartTooltip").hidden=true;return}const i=Math.max(0,Math.min(chartView.points.length-1,Math.floor(plotRatio*chartView.points.length))),p=chartView.points[i],tip=$("chartTooltip");tip.innerHTML=`<b>${esc(String(p.t).replace('T',' ').slice(0,16))}</b>开 ${num(p.o)}　高 ${num(p.h)}<br>低 ${num(p.l)}　收 ${num(p.c)}<br>RSI ${num(p.rsi14,1)}　MACD ${num(p.macd,3)}`;tip.style.left=`${Math.min(innerWidth-230,e.clientX+14)}px`;tip.style.top=`${Math.max(65,e.clientY-70)}px`;tip.hidden=false});function endDrag(e){if(!drag)return;drag=null;chart.classList.remove("dragging");try{chart.releasePointerCapture(e.pointerId)}catch{}}chart.addEventListener("pointerup",endDrag);chart.addEventListener("pointercancel",endDrag);chart.addEventListener("pointerleave",()=>{$("chartTooltip").hidden=true});chart.addEventListener("dblclick",resetWindow);
$("rangeSlider").oninput=e=>{const state=currentWindow().state;setWindow(state.count,Number(e.target.value))};$("zoomIn").onclick=()=>zoom(.8,1);$("zoomOut").onclick=()=>zoom(1.25,1);$("latestBtn").onclick=resetWindow;document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>{layers[b.dataset.layer]=!layers[b.dataset.layer];b.classList.toggle("active",layers[b.dataset.layer]);renderChart()});$("rrSlider").oninput=updateTarget;$("refreshBtn").onclick=load;$("copilotToggle").onclick=()=>$("copilot").classList.add("open");$("copilotClose").onclick=()=>$("copilot").classList.remove("open");document.querySelectorAll("[data-question]").forEach(b=>b.onclick=()=>copilotAnswer(b.dataset.question));$("notifyBtn").onclick=async()=>{if(!("Notification" in window))return toast("当前浏览器不支持系统通知");const result=await Notification.requestPermission();toast(result==="granted"?"QQQ 状态变化提醒已开启":"未获得通知权限")};
let resizeTimer=0;
addEventListener("resize",()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(analysis)renderChart()},120)});
addEventListener("visibilitychange",()=>{if(!document.hidden)load()});
load();setInterval(()=>{if(!document.hidden)load()},30000);