(() => {
  "use strict";
  const app = document.getElementById("app");
  const liveState = document.getElementById("liveState");
  const refreshButton = document.getElementById("refresh");
  const dialog = document.getElementById("holdingDialog");
  const tickerInput = document.getElementById("tickerInput");
  const symbolList = document.getElementById("symbolList");
  const editor = document.getElementById("positionEditor");
  const saveButton = document.getElementById("saveHoldings");
  const toastNode = document.getElementById("toast");
  const publicMode = Boolean(window.ANLI_PUBLIC_MODE);
  const state = {data:null,view:"holdings",eventSymbol:null,positions:[],loading:false};
  const AUTO_REFRESH = 60_000;
  const stateLabels = {DATA_GAP:"历史样本不足",EVENT_DATA_GAP:"事件需重新核验",EVENT_FREEZE:"事件优先",TREND_BROKEN:"趋势破坏",OVEREXTENDED:"向上过度延伸",WAIT_STABILIZATION:"等待企稳",REVERSION_WATCH:"回归观察",NEUTRAL:"无明显偏离"};
  const relevanceLabels = {DIRECT:"公司直接",SUPPLY_CHAIN:"产业链",SECTOR:"行业关联",GLOBAL:"全市场"};
  const e = value => String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const num = (value,digits=1) => value === null || value === undefined || !Number.isFinite(Number(value)) ? "—" : Number(value).toFixed(digits);
  const money = value => value === null || value === undefined || !Number.isFinite(Number(value)) ? "—" : `$${Number(value).toFixed(2)}`;
  const dateLabel = value => { const date=new Date(value); return Number.isNaN(date.getTime()) ? "时间待定" : new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(date); };
  const dayLabel = value => { const date=new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit"}).format(date); };
  function toast(message,error=false){toastNode.textContent=message;toastNode.style.borderColor=error?"rgba(255,111,114,.5)":"rgba(72,214,206,.45)";toastNode.classList.add("show");setTimeout(()=>toastNode.classList.remove("show"),2800)}
  async function jsonFetch(url,options={}){const response=await fetch(url,{cache:"no-store",...options});const payload=await response.json().catch(()=>({}));if(!response.ok||payload.error)throw new Error(payload.error||payload.message||`请求失败 ${response.status}`);return payload}
  function setNav(){document.querySelectorAll("[data-view]").forEach(button=>button.classList.toggle("active",button.dataset.view===state.view))}
  function quality(data){const quality=data.data_quality||{};const source=data.meta?.source||{};const ready=quality.status==="OK";return `<div class="quality ${ready?"ok":""}"><b>${ready?"✓ 数据链路正常":"i 研究闸门"}</b><span>${e(source.provider||quality.provider||"公开行情")} · ${e(source.latency||quality.latency||"时效待核验")} · ${quality.official_realtime?"已确认实时":"交易前仍需券商实时确认"}。3.2 永远不会自动下单。</span></div>`}
  function hero(data){const holdings=data.private_holdings||{};const cards=data.holding_cards||[];const events=cards.reduce((sum,row)=>sum+(row.events||[]).filter(item=>item.verified).length,0);const direct=cards.reduce((sum,row)=>sum+(row.events||[]).filter(item=>item.verified&&item.relevance==="DIRECT").length,0);const watch=cards.filter(row=>row.mean_reversion?.state==="REVERSION_WATCH").length;return `<section class="hero"><div class="hero-main"><span class="eyebrow">ANLI PRIVATE HOLDING INTELLIGENCE</span><h1>从你的持仓出发，先看<em>未来事件</em>，再谈均值回归。</h1><p>逐只股票连接公司、产业链、行业与全市场四层事件。回归研究只解释异常偏离，不把下跌自动当成机会。</p><div class="hero-actions"><button data-open-editor>管理我的持仓</button><span>${holdings.local_only?"仅保存在本机 · 版本化留痕":"隐私状态待确认"}</span></div></div><div class="hero-side"><div class="metric"><small>重点持仓</small><strong>${holdings.count||0}</strong><span>最多30只</span></div><div class="metric"><small>已核验相关事件</small><strong>${events}</strong><span>未来四个自然周</span></div><div class="metric"><small>公司直接事件</small><strong>${direct}</strong><span>优先显示</span></div><div class="metric"><small>回归观察</small><strong>${watch}</strong><span>仍非交易指令</span></div></div></section>${quality(data)}`}
  function statePill(research){const code=research?.state||"DATA_GAP";return `<span class="state state-${e(code)}">${e(research?.label||stateLabels[code]||code)}</span>`}
  function eventPreview(card){const event=card.mean_reversion?.nearest_event||(card.events||[]).find(item=>item.verified);if(!event)return `<div class="event-preview"><small>未来四周</small><strong>暂无已核验的直接或关联事件</strong><p>待核验线索不会进入风险规则。</p></div>`;const days=card.mean_reversion?.metrics?.days_to_event;return `<div class="event-preview"><small>${e(event.relevance_label||"相关事件")} ${days!==null&&days!==undefined?`· ${days}天后`:""}</small><strong>${e(event.title)}</strong><p>${dateLabel(event.at_cn||event.at_et||event.at)} · ${e(event.verification||"官方日历已核验")}</p></div>`}
  function holdingCard(card){const research=card.mean_reversion||{};const m=research.metrics||{};return `<article class="holding-card"><div class="card-top"><div class="ticker"><span class="ticker-icon">${e(card.symbol.slice(0,2))}</span><div><h3>${e(card.symbol)}</h3><p>${e(card.name)} · ${e(card.sector)}</p></div></div><div class="price"><strong>${money(card.price)}</strong><small>${e(card.source||"行情待定")}</small></div></div><div style="margin-top:14px">${statePill(research)}</div><div class="card-stats"><div><small>5日异常Z值</small><b>${num(m.zscore_5d,2)}</b></div><div><small>20日回撤</small><b>${num(m.drawdown_20d_pct,2)}%</b></div><div><small>距50日线</small><b>${num(m.distance_ma50_pct,2)}%</b></div><div><small>企稳天数</small><b>${m.stable_sessions??"—"}/3</b></div></div>${eventPreview(card)}<div class="card-footer"><p>${e(research.next_condition||"补齐数据后再研究。")}</p><button data-show-symbol="${e(card.symbol)}">查看完整研究 →</button></div></article>`}
  function holdingsView(data){const cards=data.holding_cards||[];return `${hero(data)}<div class="section-head"><div><span class="eyebrow">HOLDING COMMAND</span><h2>逐只持仓的今日研究状态</h2><p>优先级：数据缺口 → 事件冻结 → 趋势 → 异常偏离 → 企稳。</p></div></div>${cards.length?`<div class="cards">${cards.map(holdingCard).join("")}</div>`:`<section class="empty"><i>◇</i><h2>先加入你的第一只持仓</h2><p>输入股票代码即可开始重点研究；系统会自动关联未来一个月的公司、产业链、行业和宏观事件。</p><button data-open-editor>添加持仓</button></section>`}`}
  function eventRow(event){return `<div class="event ${event.verified?"":"unverified"}"><time>${dayLabel(event.at_cn||event.at)}</time><span class="relation">${e(relevanceLabels[event.relevance]||event.relevance_label||"线索")}</span><div><h4>${e(event.title)}</h4><p>${e(event.why_relevant||event.note||"")} · ${event.verified?"已核验":"待公司IR复核"}</p></div>${event.source_url?`<a href="${e(event.source_url)}" target="_blank" rel="noopener">来源 ↗</a>`:""}</div>`}
  function eventsView(data){const cards=data.holding_cards||[];if(!cards.length)return holdingsView(data);state.eventSymbol=state.eventSymbol||cards[0].symbol;const selected=cards.find(row=>row.symbol===state.eventSymbol)||cards[0];const graph=data.holding_event_graph||{};const weeks=graph.weeks||[];const rows=selected.events||[];const timeline=weeks.map(week=>{const weekRows=rows.filter(row=>row.week?.index===week.index);return `<section class="week"><div class="week-title"><b>${e(week.label)}</b><span>${e(week.start)} — ${e(week.end)}</span></div><div class="week-events">${weekRows.length?weekRows.map(eventRow).join(""):`<div class="event"><div></div><div><h4>暂无匹配事件</h4><p>本周没有进入该持仓图谱的已核验事件。</p></div></div>`}</div></section>`}).join("");const leads=rows.filter(row=>!row.verified);return `${hero(data)}<div class="section-head"><div><span class="eyebrow">FOUR-WEEK EVENT GRAPH</span><h2>${e(selected.symbol)} 的未来四周风险图谱</h2><p>公司直接 → 产业链 → 行业 → 全市场；待核验线索不改变决策状态。</p></div></div><div class="event-layout"><aside class="panel symbol-rail">${cards.map(row=>`<button class="${row.symbol===selected.symbol?"active":""}" data-event-symbol="${e(row.symbol)}">${e(row.symbol)} · ${(row.events||[]).filter(x=>x.verified).length}</button>`).join("")}</aside><div class="panel timeline">${timeline}${leads.length?`<section class="week"><div class="week-title"><b>待核验财报线索</b><span>不进入决策规则</span></div><div class="week-events">${leads.map(eventRow).join("")}</div></section>`:""}</div></div>`}
  function researchCard(card){const r=card.mean_reversion||{},m=r.metrics||{};return `<article class="panel research-card"><div class="card-top"><div class="ticker"><span class="ticker-icon">${e(card.symbol.slice(0,2))}</span><div><h3>${e(card.symbol)}</h3><p>相对 ${e(card.sector_benchmark||"QQQ")} + QQQ</p></div></div>${statePill(r)}</div><div class="signal">${num(m.zscore_5d,2)} <small>5日异常Z值</small></div><ul class="evidence">${(r.evidence||[]).map(item=>`<li>${e(item)}</li>`).join("")||"<li>历史或基准数据尚未补齐。</li>"}</ul><div class="next"><b>下一条件</b><br>${e(r.next_condition||"等待数据补齐。")}<br><br><b>失效条件</b><br>${e(r.invalidation||"—")}</div></article>`}
  function reversionView(data){const cards=data.holding_cards||[];return `${hero(data)}<div class="section-head"><div><span class="eyebrow">PRE-EVENT MEAN REVERSION</span><h2>事件前均值回归研究</h2><p>使用个股相对行业ETF与QQQ的异常偏离；仅研究，不预测财报方向，不自动下单。</p></div></div>${cards.length?`<div class="research-grid">${cards.map(researchCard).join("")}</div>`:`<section class="empty"><i>⌁</i><h2>加入持仓后开始计算</h2><p>至少需要80个共同交易日，任何数据缺口都会直接阻断结论。</p><button data-open-editor>添加持仓</button></section>`}`}
  function render(){if(!state.data)return;setNav();app.innerHTML=state.view==="events"?eventsView(state.data):state.view==="reversion"?reversionView(state.data):holdingsView(state.data);bindDynamic()}
  function bindDynamic(){document.querySelectorAll("[data-open-editor]").forEach(x=>x.onclick=openEditor);document.querySelectorAll("[data-show-symbol]").forEach(x=>x.onclick=()=>{state.eventSymbol=x.dataset.showSymbol;state.view="reversion";render();window.scrollTo({top:0,behavior:"smooth"})});document.querySelectorAll("[data-event-symbol]").forEach(x=>x.onclick=()=>{state.eventSymbol=x.dataset.eventSymbol;render()})}
  function renderEditor(){editor.innerHTML=state.positions.length?state.positions.map((row,index)=>`<div class="position-row"><b>${e(row.symbol)}</b><input class="optional-sector" data-field="sector" data-index="${index}" value="${e(row.sector||"")}" placeholder="行业（选填）"><input class="optional-qty" data-field="quantity" data-index="${index}" value="${e(row.quantity||"")}" inputmode="decimal" placeholder="数量"><input class="optional-cost" data-field="average_cost" data-index="${index}" value="${e(row.average_cost||"")}" inputmode="decimal" placeholder="成本"><input class="optional-stop" data-field="stop_price" data-index="${index}" value="${e(row.stop_price||"")}" inputmode="decimal" placeholder="止损"><button type="button" data-remove="${index}" aria-label="移除">×</button></div>`).join(""):`<p class="form-hint">当前没有持仓。你也可以保存空列表来清除私人持仓。</p>`;editor.querySelectorAll("input[data-field]").forEach(input=>input.oninput=()=>state.positions[Number(input.dataset.index)][input.dataset.field]=input.value.trim());editor.querySelectorAll("[data-remove]").forEach(button=>button.onclick=()=>{state.positions.splice(Number(button.dataset.remove),1);renderEditor()})}
  function openEditor(){state.positions=(state.data?.private_holdings?.positions||[]).map(row=>({symbol:row.symbol,sector:row.sector==="未分类"?"":row.sector||"",quantity:row.quantity||"",average_cost:row.average_cost||"",stop_price:row.stop_price||""}));document.getElementById("saveHint").textContent=publicMode?"公开版只写入这个浏览器；不会上传服务器。":"持仓保存在本机，不会上传到公开网站。";document.getElementById("editorHint").textContent=publicMode?"公开版可选择当前52股股票池；股票池外代码请在本机3.2验证。":"支持列表内选择，也支持输入其他有效美股代码；新代码会先验证公开行情。";renderEditor();dialog.showModal();tickerInput.focus()}
  function addTicker(){const symbol=tickerInput.value.trim().toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,9}$/.test(symbol))return toast("请输入有效的美股代码",true);if(state.positions.some(row=>row.symbol===symbol))return toast(`${symbol} 已在列表中`,true);if(state.positions.length>=30)return toast("最多跟踪30只持仓",true);state.positions.push({symbol,sector:"",quantity:"",average_cost:"",stop_price:""});tickerInput.value="";renderEditor()}
  async function saveHoldings(){saveButton.disabled=true;saveButton.textContent="正在验证行情…";try{const positions=state.positions.map(row=>Object.fromEntries(Object.entries(row).filter(([,value])=>value!=="")));await jsonFetch("/api/v3.2/holdings",{method:"POST",headers:{"Content-Type":"application/json","X-ANLI-Confirm":"holdings-update","Idempotency-Key":`holdings-${Date.now()}-${Math.random().toString(16).slice(2)}`},body:JSON.stringify({positions})});dialog.close();toast("持仓已保存，正在重算四周事件和异常偏离");await load(true)}catch(error){toast(error.message,true)}finally{saveButton.disabled=false;saveButton.textContent="确认保存"}}
  async function load(manual=false){if(state.loading)return;state.loading=true;refreshButton.classList.add("spin");try{const data=await jsonFetch("/api/v3.2/dashboard");state.data=data;liveState.classList.add("ok");liveState.querySelector("span").textContent=`自动刷新 · ${new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`;symbolList.innerHTML=(data.symbols||[]).map(row=>`<option value="${e(row.symbol)}">${e(row.name||"")} · ${e(row.sector||"")}</option>`).join("");render();if(manual)toast("已获取最新持仓研究") }catch(error){liveState.classList.remove("ok");liveState.querySelector("span").textContent="连接失败";if(!state.data)app.innerHTML=`<section class="empty"><i>!</i><h2>3.2 暂时无法连接</h2><p>${e(error.message)}</p><button id="retry">重新连接</button></section>`,document.getElementById("retry").onclick=()=>load(true);else toast(error.message,true)}finally{state.loading=false;refreshButton.classList.remove("spin")}}
  document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>{state.view=button.dataset.view;render();window.scrollTo({top:0,behavior:"smooth"})}));
  document.getElementById("addTicker").onclick=addTicker;tickerInput.onkeydown=event=>{if(event.key==="Enter"){event.preventDefault();addTicker()}};saveButton.onclick=saveHoldings;refreshButton.onclick=()=>load(true);dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});
  load();setInterval(()=>{if(!document.hidden)load()},AUTO_REFRESH);
})();
